--Student functionality related data

--Student table
CREATE TABLE STUDENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    PERSONAL_CODE BIGINT
 );

--Student data
INSERT INTO STUDENT (NAME, SURNAME, PERSONAL_CODE) VALUES ('Pirmas', 'Test', 69846387985);
INSERT INTO STUDENT (NAME, SURNAME, PERSONAL_CODE) VALUES ('Antras', 'Test', 985498968965);
INSERT INTO STUDENT (NAME, SURNAME, PERSONAL_CODE) VALUES ('Trecias', 'Test', 896534988665);

--Update auto increment as we inserted already 3 values
ALTER TABLE STUDENT ALTER COLUMN ID RESTART WITH 4;